dbfilename redis_queue.rdb
dir /home/nazmul/Desktop/MyProjects/softife_saas/config/pids
pidfile /home/nazmul/Desktop/MyProjects/softife_saas/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/nazmul/Desktop/MyProjects/softife_saas/config/redis_queue.acl
